language: ruby

install:
  - gem uninstall bundler
  - gem install bundler --version '1.16.3'

rvm:
  - 2.7.0

services:
- postgresql

before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate

script:
- bundle exec rspec
- bundle exec rubocop -DESP
